import type { ImportWorkout } from "./types";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;
const ISO_TIMESTAMP = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{3})?Z$/;

function assertUserId(userId: string): void {
  if (!UUID.test(userId)) throw new Error(`Not a user id: ${userId}`);
}

/**
 * A dollar-quoted literal's tag must not appear inside the text it quotes,
 * or the quote ends early and the rest is parsed as SQL. Check every tag
 * that wraps this text, including an outer do-block tag the text sits
 * inside of.
 */
function assertNoQuoteClash(context: string, text: string, tags: string[]): void {
  for (const tag of tags) {
    if (text.includes(tag)) throw new Error(`${context} contains the ${tag} quote tag`);
  }
}

/** Runs the block as the owner: RLS then proves every row is theirs. */
function actAs(userId: string): string {
  return `  execute 'set local role authenticated';
  perform set_config('request.jwt.claims',
    json_build_object('sub', '${userId}', 'role', 'authenticated')::text, true);`;
}

function buildPayload(workouts: ImportWorkout[]) {
  const names = [...new Set(workouts.flatMap((w) => w.exercises.map((e) => e.name)))].sort();
  const options = new Map<string, { name: string; key: string; values: Set<string> }>();
  for (const exercise of workouts.flatMap((w) => w.exercises)) {
    for (const [key, value] of Object.entries(exercise.attributes)) {
      const id = `${exercise.name}\u0000${key}`;
      const entry = options.get(id) ?? { name: exercise.name, key, values: new Set<string>() };
      entry.values.add(value);
      options.set(id, entry);
    }
  }
  return {
    lastDate: workouts.map((w) => w.performedOn).sort().at(-1) ?? null,
    exerciseNames: names,
    attributeOptions: [...options.values()].map((o) => ({ name: o.name, key: o.key, values: [...o.values].sort() })),
    workouts: workouts.map((w) => ({
      performedOn: w.performedOn,
      category: w.category,
      note: w.note,
      exercises: w.exercises.map((e) => ({
        name: e.name,
        note: e.note,
        attributes: e.attributes,
        sets: e.sets.map((s) => [s.weightKg, s.reps, s.uncleanReps, s.isWarmup, s.isDropset]),
      })),
    })),
  };
}

/**
 * One DO block = one transaction: everything lands or nothing does.
 * dry-run ends in `raise exception`, which rolls the whole block back after
 * reporting the counts (same pattern as supabase/checks/dashboard_views.sql).
 */
export function emitImportSql(
  workouts: ImportWorkout[],
  options: { userId: string; mode: "dry-run" | "commit" }
): string {
  assertUserId(options.userId);
  const payload = buildPayload(workouts);
  if (!payload.lastDate || !ISO_DATE.test(payload.lastDate)) throw new Error("Nothing to import");
  const json = JSON.stringify(payload);
  // The payload sits inside `$payload$...$payload$`, which itself sits
  // inside the outer `do $import$...$import$` block — either tag appearing
  // in the text would truncate its quote early.
  assertNoQuoteClash("Import text", json, ["$payload$", "$import$"]);

  const finish =
    options.mode === "dry-run"
      ? `  raise exception 'NOTES_IMPORT_DRY_RUN_OK workouts=% exercises=% sets=% new_exercise_names=%',
    n_workouts, n_exercises, n_sets, n_new_names;`
      : `  raise notice 'NOTES_IMPORT_DONE workouts=% exercises=% sets=% new_exercise_names=%',
    n_workouts, n_exercises, n_sets, n_new_names;`;

  // Run in both modes: the dry run should rehearse the same abort a commit
  // would hit, so a dry run that passes is a reliable preview of a commit.
  const guard = `  if exists (select 1 from workouts where user_id = me and performed_on <= (payload->>'lastDate')::date) then
    raise exception 'NOTES_IMPORT_ABORT: workouts up to % already exist', payload->>'lastDate';
  end if;
`;

  return `-- Notes-file import (${options.mode}). Generated by scripts/notes-import.ts — do not commit.
do $import$
declare
  me constant uuid := '${options.userId}';
  payload constant jsonb := $payload$${json}$payload$;
  w jsonb;
  x jsonb;
  s jsonb;
  v_workout uuid;
  v_workout_exercise uuid;
  v_exercise uuid;
  stamp timestamptz;
  exercise_position int;
  set_position int;
  n_workouts int := 0;
  n_exercises int := 0;
  n_sets int := 0;
  n_new_names int := 0;
begin
${actAs(options.userId)}

${guard}
  with inserted as (
    insert into exercises (user_id, name)
    select me, name from jsonb_array_elements_text(payload->'exerciseNames') as t(name)
    on conflict (user_id, name) do nothing
    returning 1
  )
  select count(*) into n_new_names from inserted;

  for w in select * from jsonb_array_elements(payload->'workouts') loop
    -- Noon Berlin time: a stable, plausible created_at on the right day.
    stamp := ((w->>'performedOn')::date + time '12:00') at time zone 'Europe/Berlin';
    insert into workouts (user_id, performed_on, category, note, created_at)
    values (me, (w->>'performedOn')::date, w->>'category', w->>'note', stamp)
    returning id into v_workout;
    n_workouts := n_workouts + 1;

    exercise_position := 0;
    for x in select * from jsonb_array_elements(w->'exercises') loop
      select id into strict v_exercise from exercises where user_id = me and name = x->>'name';
      insert into workout_exercises (workout_id, exercise_id, position, note, attributes, created_at)
      values (v_workout, v_exercise, exercise_position, x->>'note', x->'attributes',
              stamp + make_interval(secs => exercise_position))
      returning id into v_workout_exercise;
      n_exercises := n_exercises + 1;

      set_position := 0;
      for s in select * from jsonb_array_elements(x->'sets') loop
        insert into sets (workout_exercise_id, position, weight_kg, reps, unclean_reps,
                          is_warmup, is_dropset, created_at)
        values (v_workout_exercise, set_position, (s->>0)::numeric, (s->>1)::int, (s->>2)::int,
                (s->>3)::boolean, (s->>4)::boolean, stamp);
        set_position := set_position + 1;
        n_sets := n_sets + 1;
      end loop;
      exercise_position := exercise_position + 1;
    end loop;
  end loop;

  -- Selectable variations: union what the import used into each exercise.
  for x in select * from jsonb_array_elements(payload->'attributeOptions') loop
    update exercises e
       set attribute_options = e.attribute_options || jsonb_build_object(
             x->>'key',
             (select jsonb_agg(distinct v order by v)
                from jsonb_array_elements_text(
                       coalesce(e.attribute_options->(x->>'key'), '[]'::jsonb) || (x->'values')) as t(v)))
     where e.user_id = me and e.name = x->>'name';
  end loop;

  -- The insert trigger stamped every imported exercise "picked now", which
  -- would float two-year-old exercises to the top of the picker. Recompute
  -- from the rows, exactly like the backfill in 20260915203912.
  update exercises e
     set last_picked_at = picked.last_picked_at
    from (select exercise_id, max(created_at) as last_picked_at
            from workout_exercises group by exercise_id) picked
   where picked.exercise_id = e.id and e.user_id = me;

${finish}
end
$import$;
`;
}

export function emitRollbackSql(options: {
  userId: string;
  lastDate: string;
  generatedAt: string;
  /** The import's `payload.exerciseNames` — scopes the exercise delete to what the import itself named. */
  exerciseNames: string[];
}): string {
  assertUserId(options.userId);
  if (!ISO_DATE.test(options.lastDate)) throw new Error(`Not a date: ${options.lastDate}`);
  if (!ISO_TIMESTAMP.test(options.generatedAt)) throw new Error(`Not a timestamp: ${options.generatedAt}`);

  const namesJson = JSON.stringify(options.exerciseNames);
  // The names sit inside `$names$...$names$`, which itself sits inside the
  // outer `do $rollback$...$rollback$` block.
  assertNoQuoteClash("Exercise name", namesJson, ["$names$", "$rollback$"]);

  return `-- Undo the notes-file import. App data starts 2026-08-19, the log ends ${options.lastDate}.
do $rollback$
declare
  me constant uuid := '${options.userId}';
  names constant jsonb := $names$${namesJson}$names$;
begin
${actAs(options.userId)}

  -- Removes every workout of the owner on or before lastDate, including any
  -- backdated later by hand — the import never creates workouts after this date.
  delete from workouts where user_id = me and performed_on <= '${options.lastDate}';

  -- Only exercises the import created (after generation), named by the
  -- import's own payload, and nothing uses now — an exercise the owner
  -- created by hand after the import keeps its rows even if unreferenced.
  delete from exercises e
   where e.user_id = me
     and e.created_at >= '${options.generatedAt}'
     and e.name = any(array(select jsonb_array_elements_text(names)))
     and not exists (select 1 from workout_exercises we where we.exercise_id = e.id);

  update exercises e
     set last_picked_at = (select max(we.created_at) from workout_exercises we where we.exercise_id = e.id)
   where e.user_id = me;
end
$rollback$;
`;
}
